"""add points_balance to customer

Revision ID: fb16f5a8ef93
Revises: ad76b339aff2
Create Date: 2026-01-21 17:45:01.575103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb16f5a8ef93'
down_revision: Union[str, Sequence[str], None] = 'ad76b339aff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('points_balance', sa.Integer(), nullable=False,
    server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'points_balance')
    # ### end Alembic commands ###
